### ISSUE TITLE
Points and other features possible?

### ISSUE THREAD

**Issue by thorstengrothe** [Strauman/exercisebank#45]
Hi,

I like the idea of your package to keep things as simple as possible. I tried over the years many latex exam packages, the most important are `eqexam` and `xsim`. The problem with these packages is, that they have to much overload for my daily work. `Eqexam/Acrotex` needs Adobe Acrobat to run and `xsim` is very very slow at compile time, that's nothing for my daily work as a teacher with lot's of different courses and many different exams.

So I looked at your package and it seems to be lightweight and fast. I miss a couple of things/features.

1. Tagging problems like in xsim
2. The calculation of points with bonus points like xsim/eqexam would be a very important feature for my work.
3. Blank lines for the students to write something in as well.

Is that possible with your package?

Regards
Thorsten

**Comment by Strauman** [comment]
Hello thorstengrothe, and thank you for your interest in exercisebank.

1. Tagging problems are definitely on the todo-list. To make sure that it is the functionality that you want, head over to #2 and make sure? :)
2. Points are not planned as a built-in feature, but I will consider it.
3. This is something that should be fairly easy to implement without having it inside the package! Just use the solution environment! E.g.
```
\begin{solution}
\hrulefill\par\hrulefill
\end{solution}
```

**Comment by thorstengrothe** [comment]
Hello,

> This is something that should be fairly easy to implement without having it inside the package! Just use the solution environment! E.g.

Thanks a lot for the hint. I modified the code a bit and got a working command, the only thing I don't know how to to do is a check function to test if the command is executed in a `problem` or `solution` environment. See my attached example. Do you have an idea?
```
\documentclass{article}
\usepackage{expl3,setspace,ulem,xcolor}

% Repeat something n times needs \usepackage{expl3}
\ExplSyntaxOn%
\cs_new_eq:NN \ntimes \prg_replicate:nn%
\ExplSyntaxOff

\newcommand{\blanknostar}[3]{%
	% If in normal environment
	\ntimes{#1}{%
	\begin{spacing}{#2}
	\par\hrulefill\par
	\end{spacing}}
	% If in solution environment
	%\textcolor{red}{\uline{#3}}
}

\newcommand{\blankstar}[1]{%
	% If in normal environment
	\hrulefill\par
	% If in solution environment
	%\textcolor{red}{\uline{#3}}
}

% Define blank and blank*
\makeatletter
\newcommand\blank{\@ifstar\blankstar\blanknostar}
%\g@addto@macro{\solution}{\blanknostarred}
\makeatother

\begin{document}

\blank{8}{1.2}{Test}

\end{document}
```

**Comment by Strauman** [comment]
You can try adding a flag in the begin/end solution-hooks:

```
\newif\ifisSolution
\At\BeginSolution{\global\isSolutiontrue}
\At\EndSolution{\global\isSolutionfalse}
```
and then
```
\newcommand{\blanknostar}[3]{%
        % If in solution environment
        \ifisSolution
	  %\textcolor{red}{\uline{#3}}
	% If in normal environment
         \else
	  \ntimes{#1}{%
	  \begin{spacing}{#2}
	  \par\hrulefill\par
	  \end{spacing}}
        \fi
}
```
There are more triggers, which of most are documented on page 12 in the [docs](http://mirrors.ctan.org/macros/latex/contrib/exercisebank/exercisebank-doc.pdf).
 All are used with the same syntax `\At\HookName{}`.

**Comment by thorstengrothe** [comment]
Ah I see a hook, yes this works fine now. I'm working on another new command adapted from eqexam which I use very often. I need some time for testing it. I you are interested I can post the final commands here, maybe you can use it for the package.

The next thing are points and autopoints, as I said this feature is essential for me, when I remember it right, tocolorbox has something, I will look and report.

Thanks for the fast help

Regards
Thorsten

**Comment by Strauman** [comment]
I'll be happy to include any command that you'd develop. It'd be awesome if you implemented it and using a [pull request](https://help.github.com/articles/creating-a-pull-request/).

**Comment by Strauman** [comment]
Also: what is this command, from eqexam, you speak of?

**Comment by Strauman** [comment]
@thorstengrothe I cannot unzip the NewCommands.zip-file?

**Comment by thorstengrothe** [comment]
Ok, sorry zip file was corrupt, this should work...

[NewCommands.zip](https://github.com/Strauman/exercisebank/files/2303509/NewCommands.zip)

**Comment by tristelune1** [comment]
Hi, I'm also very interested by the following features:

1. tag system
2. the possibilities to add points

A tag system would be convenient, but I can wait. For the "points" feature" it's also essential for me. Do you know a workaround ? For me Something like

**Exercise 1 (2 Points)**

Would be already fine.

**Comment by thorstengrothe** [comment]
Well, I think we have to define some counters and assign them to the problem environments. I found one promising package, see link [here](https://tex.stackexchange.com/questions/347469/total-number-of-points/347471). I guess it should  be hopefully possible with this package...

**Comment by thorstengrothe** [comment]
A first rough workaround is working fine here with a small sideeffect
```
\usepackage{totcount,marginnote}
% Counters, needs \usepackage{totcount, marginnote}
\newtotcounter{problempoints}
\newcommand{\problemsum}{\the\numexpr\totvalue{problempoints}}
\newcommand{\points}[1]{%
  \marginnote{\rule{1cm}{1pt}~/#1}
  \addtocounter{problempoints}{#1}
}
```
Assign `\points` under the problem header and run latex 2 times. Add `\problemsum` after `\begin{document}` and you got the total sum of the problem points. The sideeffect is, that the first line after the problem counter is indented, because there is the command `\points`. I have no clue how to avoid that at the moment.

**Comment by Strauman** [comment]
@thorstengrothe @tristelune1 
I will add points for the next release. I'm working on a little more complicated workaround for now, and I will share it at [tex.SE](https://tex.stackexchange.com) when it's ready. Please ask _questions_, and share workarounds, over there :)

**Comment by Strauman** [comment]
Maybe I wasn't clear in the previous message: I still _really_ appreciate your activity and input!

**Comment by Strauman** [comment]
You can find the workaround [here](https://tex.stackexchange.com/a/447141/85834): https://tex.stackexchange.com/a/447141/85834

**Comment by thorstengrothe** [comment]
@Strauman 

> Maybe I wasn't clear in the previous message: I still really appreciate your activity and input!

No  problem, I'm glad if I can help a bit :-) I will comment your workaround on tex.exchange

**Comment by Strauman** [comment]
@thorstengrothe @tristelune1 I have published a [pre-release here](https://github.com/Strauman/exercisebank/releases/tag/0.2.1-prerelease) that supports tagging. In the zip-file there is updated documentation with the tagging documentation added.

**Comment by tristelune1** [comment]
**@ Strauman**

> @thorstengrothe @tristelune1 I have published a pre-release here that supports tagging. In the zip-file there is updated documentation with the tagging documentation added. Please test and give feedback!

Thank you very much!! I will test as soon as possible. 

Thank you for your workaround on tex.SE. [The idea of thor](https://tex.stackexchange.com/a/447217/164657) is also very good.

**Comment by thorstengrothe** [comment]
@Strauman 
Me too, I download tomorrow and test. I wrote a comment [here](https://tex.stackexchange.com/questions/447140/how-to-add-exercise-points-to-package-exercisebank/447217#447217). The command `\totalpoints` has run after the `\buildset`. But I have a titlepage before the problems with `\totalpoints` in it. Is this fixable? If you run `\ShowNumbers` with your `newcommand` the numbers and the `partproblem` header are mixed up at least on my mashine. Maybe trivial.

Thanks for your work!

**Comment by Strauman** [comment]
@thorstengrothe I didn't see this until now. Did you get this fixed?

**Comment by thorstengrothe** [comment]
Yes, but you need another package `\usepackage{totcount} ` and `\usepackage{marginnote}`
I'm a big fan of the KISS principle - but I have no clue how to avoid this in this case. But it works here fine. This is my modified code:
```
\makeatletter
 % Make a counter for accumulating points \newcounter{problempoints} % old version
 \newtotcounter{problempoints} % totcount version
 % For readability, defining \let\totalpoints\theproblempoints % old version
 \newcommand{\totalpoints}{\the\numexpr\totvalue{problempoints}} % totcount version
 % \currentPoints is a placeholder for the number of points the current part
 % problem has
 \gdef\currentPoints{0}
 % Disable the default part problem header made by exercisebank
 \exercisebanksetup{part problem header={\relax}}
 % Make a new command to insert part problem header (inspired by the default
 % found on page 10 in the manual):
 \def\ppheader{%
   \leavevmode%
   \smash{%
     \llap{%
       {\large\textbf{\theproblemcounter.\arabic{partproblemcounter}~)}}%
%        if \currentPoints contains 0, \currentPoints aren't printed.
%        \ifnum\currentPoints=\z@\else\currentPoints p\fi~}}\ignorespaces%
       \ifnum\currentPoints=\z@\else\marginnote{\rule{1cm}{.5pt}~/\currentPoints % marginnote version
         P.} \fi}}\ignorespaces%
 }
 % Reset \currentPoints, so that if no points are set in the next, nothing would
 % be added
 \At\EndPartproblem{\gdef\currentPoints{0}}
 % Make a new command that sets the current points and increases the
 % total-counter
 \newcommand\addpoints[1]{%
   \gdef\currentPoints{#1}%
   \addtocounter{problempoints}{#1}%
   \ppheader}
 \makeatother
```
 This way you set  `\totalpoints`  before the `\buildset` command and it shows the correct sum of points.
