### ISSUE TITLE
\makeset[intro] not working in example files bug?

### ISSUE THREAD

**Issue by thorstengrothe** [Strauman/exercisebank#50]
1. I tried this command with the shipped example files:
`\makeset[intro]{1}{firstexercise}`
 and got this error message:
`! LaTeX Error: Something's wrong--perhaps a missing \item.`

2. The next thing is, that first line of the intro content is indented to the right like so:
![indent](https://user-images.githubusercontent.com/19598706/44632752-5f9f8d00-a980-11e8-94a8-69a86ba883b1.png)
I got `style margins=no` to get everything aligned to the left side. If I set
```
\begin{intro}
   \par
   \vspace{-1\baselineskip}
   \lipsum[1-1]
\end{intro}
```
if works fine.

Regards
Thorsten

**Comment by Strauman** [comment]
For the 2nd thing, try `\setlength\parindent{0pt}`. I'll look into the first.

**Comment by Strauman** [comment]
@thorstengrothe I can't reproduce the first one. All the example files are auto-built for testing purposes when the `.sty`-file is built. Are you sure you have the `\begin` and `\end` `intro`, `problem` and `solution` on their own line with no other text whatsoever?

**Comment by Strauman** [comment]
Reproduced with `\makeset[intro]{11}{\exclude{secondexercise}{1}}`

**Comment by Strauman** [comment]
@thorstengrothe Please check now. Thanks

**Comment by thorstengrothe** [comment]
The intro command is working now fine. I can hide and display with

```
\makeset[intro]{2}{\select{secondexercise}{2}}
\buildset{2}
```
Now `\ShowNumbers` does not work, I make a new issue for that
