### ISSUE TITLE
\ShowNumbers produces strange numbers

### ISSUE THREAD

**Issue by thorstengrothe** [Strauman/exercisebank#51]
When I set 

`\ShowNumbers` in your example files I got this plus intro does not have a number.

![shownumbers](https://user-images.githubusercontent.com/19598706/44733880-d192e600-aae8-11e8-8f99-82bb9bb6b7ec.png)

And also, how can I change the attributes (font and color) of the command? Say, I would like yellow big sans serif numbers with a bit more distance to the text, is that possible?

**Comment by Strauman** [comment]
> `\ShowNumbers` in your example files I got this
That's a very interesting behaviour!

> plus intro does not have a number.
Are you running `\makeset` with `[intro]`?  It shows up here but is very malplaced

> And also, how can I change the attributes (font and color) of the command? Say, I would like yellow big sans serif numbers with a bit more distance to the text, is that possible?
What command are you talking about here?

**Comment by thorstengrothe** [comment]
Yeah, I'm running  `\makeset` with `\intro`

I'm talking about `\ShowNumbers ` I would like to customize it a bit: distance to the text, color and font attributes ...

**Comment by Strauman** [comment]
`\ShowNumbers` is mostly a tool for using `\select` and `\exclude`. However, it can be done by redefining `\themetacounter`. The following should work:

```
\let\oldmetacounter\themetacounter
\def\themetacounter{{\color{green}\oldmetacounter~}}
```

**Comment by Strauman** [comment]
This should now be fixed on the [develop branch](https://github.com/Strauman/exercisebank/tree/develop)

**Comment by thorstengrothe** [comment]
Ok, no problem .. I found the next one :-)
But here are good news. I made a complete exam `exercisebank` today and it works pretty well. Better than `xsim` IMO :-)

**Comment by Strauman** [comment]
> Ok, no problem .. I found the next one :-)

I don't understand. Found the next what?

>I made a complete exam exercisebank today and it works pretty well. Better than xsim IMO :-)

@thorstengrothe Great to hear that someone are using `exercisebank` and that it's working as expected. Really appreciate your help in testing and feedback, and I'll give you some credit in the docs of the upcoming version!

**Comment by thorstengrothe** [comment]
I'm sorry, I thought I found a new bug, I tried underscores in the exercise file names and get an error with `Auctex`. Then I tried it with `Texstudio` and it works. It's an `Auctex` issue and has nothing to do with `exercisebank`. I will investigate and report what's wrong with `Auctex`. Sorry for the noise.

**Comment by Strauman** [comment]
@thorstengrothe Yeah - underscores in filenames are often a problem. Try escaping them using a leading `backslash`.
