### ISSUE TITLE
Selection of multiple problems

### ISSUE THREAD

**Issue by tristelune1** [Strauman/exercisebank#54]
Hi, 
I have tested the version 0.2.1 (b81) and there is an issue when selecting multiple problems. I do the following to select multiple problems:
```
    \makeset[nohead]{myExerciseSet}{\select{databaseNombres}{18,...,35}}
    \DisplaySolutions
    \ShowNumbers
    \translateExBank{Problem=Exercice}
    \buildset{myExerciseSet}
```

Only the Problem 18 from the file "databaseNombres.tex" is displayed. 

With version 0.2 there is no problem.

**Comment by Strauman** [comment]
Do you experience this only when you use the `...`?

**Comment by tristelune1** [comment]
Yes, otherwise it works.

**Comment by Strauman** [comment]
@tristelune1 Is this (the `...`) functionality you deem important for the package? It's a consequence of switching to a more light weight looping system, and reimplementing it would probably trade off a bit of speed if you have many exercises. I'd like to hear your opinion on this?

**Comment by tristelune1** [comment]
@Strauman  This functionality is convenient, not important. With the experience from xsim, For the moment I prefer speed over a little convience. My arguments are the following:

1. I didn't try, but I think
`` \makeset[nohead]{myExerciseSet}{\select{databaseNombres}}``
select all exercises from "databaseNombres". If yes, there is already a way to display all exercises and to select the ones we want.
2. The tag system is more important. We could choose all exercises with a certain tag. If really necessary, we could tag all the exercises we want to have a look and then print them. After we delete the tag.
3. I mainly use this package to create exercise sheets. If I have 10 exercises for a sheet, it's already a lot. So I could enter the numbers. And there is also the same argument as before: I could tag all the exercises I want with "exsheet1" and print all exercises with that tag. 

Perhaps I miss something, but for the moment there are other functionalities to implements and perhaps in the future it will be clear this functionality can be droped. But for the moment for sure the documentation has to be modified.

**Comment by tristelune1** [comment]
If you fix the support for the dots, the documentation doesn't need any modification. For sure, one second more isn't so important. 
And yes I'm eager to be able to use multiple tags!

**Comment by Strauman** [comment]
@tristelune1  Multiple tags should now be possible with just using `\nextproblem{tags={list,of,tags}}`
