### ISSUE TITLE
Pathcontrol doesn't work as expected.

### ISSUE THREAD

**Issue by tristelune1** [Strauman/exercisebank#56]
Hi,

I have a lot of problems, so they are stored in external files. I include also some pictures in my problems and I have centralized them in a folder. For examples, my problems are in

 - /home/user/Documents/exercises/geometry/databaseGeometry.tex
 - /home/user/Documents/exercises/numbers/databaseNumbers.tex

and the pictures

  - /home/user/Documents/pictures/math/geometry/
 - /home/user/Documents/pictures/math/numbers/

So I used "figure root directory":

```
\exercisebanksetup{exercise
  directory=/home/user/Documents/exercises/,
figure root directory=/home/users/Documents/pictures/math/,
part problems=Off}
```

So in order to include a picture I have to do:

    \includegraphics{numbers/mypicture}

Unfortunately it doesn't work. After searching, I discoverd it works if my external files are all in the same directory. For example:
 - /home/user/Documents/exercises/databaseGeometry.tex
 - /home/user/Documents/exercises/databaseNumbers.tex

The structure for the pictures is the same. Is it intentional ? I read nothing in the documentation, can't we mention it ? It would be good to split external files in several directories, but other features are more important at the moment I think.

**Comment by tristelune1** [comment]
1. Without a trailing at the end, it doesn't work. I didn't test your second option. Let's take an example. For geometry exercises, I use sometimes pictures of planets of the solar system, let's say Mars or Jupiter. I want to have like a "database" of pictures. I could use those pictures in other documents, perhaps they have nothing to do with geometry exercises. For me it's much easier to put the pictures in a directory like

    ``/home/user/Documents/pictures/universe/mars.png``
     ``/home/user/Documents/pictures/universe/jupiter.png``

But It make sense to have all geometry exercises in 
     ``/home/user/Documents/exercises/geometry/databaseGeometry.tex``

2. Perhaps, but it depends, if you want to change your code. 
3. I would expect exactly the same as ``\graphicspath`` from the package hyperref. If I have

``\graphicspath{{/home/user/Documents/picture/}}``

With a picture in 

    /home/user/Documents/pictures/universe/jupiter.png

I have to write the missing part of the path:

    \includegraphics{universe/jupiter.png}

If a user has pictures only related to exercises, your solution is probably better. For pictures related to multiple exercises (geometry or length for example) and also for other documents (math, physics, history for example), the second solution is probably better.

**Comment by Strauman** [comment]
@tristelune1 It's actually governed by `\graphicspath` and `\input@path` in the [pathcontrol.tex](https://github.com/Strauman/exercisebank/blob/develop/src/pathcontrol.tex)-file, and the scenario you describe _should_ work I think. However, I'll try to reproduce and get back to you :)

**Comment by Strauman** [comment]
@tristelune1 Does the paths work as expected after the last few fixes?

**Comment by Strauman** [comment]
Works fine here? You shouldn't set `\graphicspath` yourself - exercisebank does it for you. Would you check out the docs on this to make sure you're doing it right and, if you are doing it right, make a new reproducable example?

**Comment by tristelune1** [comment]
So here is what I tested, what I know.

Main file: main.tex:
````
\documentclass[a4paper]{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[french]{babel}
\usepackage{graphicx}
\usepackage{exercisebank}
\usepackage{caption}
\usepackage{amsmath}
\usepackage{etoolbox}

\title{My exercises}

\exercisebanksetup{exercise
  directory=/home/user/Mes_Documents/prof/cours_exercices/,
figure root
directory=/home/user/Mes_Documents/prof/cours_images/math/,
part problems=true,
tighten paragraphs=false}


\makeset{myExerciseSet}{test1/ex1,test2/ex2}


\DisplaySolutions
\translateExBank{Problem=Exercice}

\begin{document}


\maketitle{}

\buildset{myExerciseSet}

\end{document}
````

In this configuration it works without problems. But has soon has an exercise has a picture, it doesn't work anymore. Path of first exercise:

    /home/user/Mes_Documents/prof/cours_exercices/test1

In that folder there the exercise ex1.tex.

ex1.tex:

````
\begin{problem}
  Prob 1
\end{problem}
\begin{solution}
  Solution 1
\end{solution}
````

Second exercise file ex2.tex. Path:

    /home/user/Mes_Documents/prof/cours_exercices/test2

In that folder there the exercise ex2.tex.

ex2.tex:

````
\begin{problem}

  Problem 1

\begin{figure}[!h]
  \makebox[\textwidth]{
    \includegraphics[scale=0.3]{fractions/couches_peinture}   }
\end{figure}

\end{problem}
\begin{solution}
  Solution 1
\end{solution}
````

The picture "couche_peinture" is in the folder: 

    /home/user/Mes_Documents/prof/cours_images/math/fractions


With a picture this, time, the compilation failed. It's possible to solve the problem with the following change in the main file:

````
\exercisebanksetup{exercise
  directory=/home/user/Mes_Documents/prof/cours_exercices/test2,
figure root
directory=/home/user/Mes_Documents/prof/cours_images/math/,
part problems=true,
tighten paragraphs=false}


\makeset{myExerciseSet}{../test1/ex1,ex2}
````

But as soon as ex1.tex has also a picture, it doesn't work anymore.

**Comment by Strauman** [comment]
I don't know why I didn't think of this before, but you can append to the graphicpaths:
```\makeatletter
\def\addtographicpath#1{%
\g@addto@macro\Ginput@path{#1}
}
\makeatletter
\addtographicpath{{path/to/other/figures}{path/to/even/more/figures/}}

```

**Comment by Strauman** [comment]
Should be fixed in b125
