### ISSUE TITLE
Can the titles "problem" and "solution" be changed?

### ISSUE THREAD

**Issue by mayoutu** [Strauman/exerciseBank#6]
The default setting is "problem" and "solution" but can they be changed? I hope Chinese characters can be used instead, thank you!

**Comment by Strauman** [comment]
Hello @mayoutu! 
Thank you for asking and using the package:

Yes, this can be done by writing
```
\translateExBank{Problem=TranslationOfProblem, Solution=TranslationOfSolution}
```
I don't know if Chinese characters would work, but give it a go! If it doesn't work, then please open a new issue and let me know. When it comes to part problems ( 1a, 1b ) etc, this is not changeable right now, but is planned to go out on the next release in issue #5.

Hope this answers your question!

**Comment by mayoutu** [comment]
I tried and it says undefined control sequence.

Another problem is this:

I made several TEX files of problems and each file has a couple. When I make a setup using all of them, and display the solutions, the paragraphing is poor. After some solutions, the next problem comes right after; after other solutions, it leaves a big blank and the next problem comes at the next page. What's the cause and can I control that? Thanks!

**Comment by Strauman** [comment]
That is very weird. It works fine when I do it. Does it work without the Chinese characters?

Regarding the paragraphs: yes, I am aware of this problem, and I will fix it on the next release. Added an issue #7

**Comment by mayoutu** [comment]
The command works now but it doesn't support Chinese characters (the main document has no trouble reading them since I include certain packages).

As I set narrow side margins, the title becomes incomplete. How can I upload a figure that shows the margin problem and the paragraphing problem, too?

Thanks for the help and your package!

**Comment by Strauman** [comment]
I really want this package to work properly, so I would like to know of the problems with it.
The paragraphing problem is being taken care of. 

If you don't mind: please create two new issues
- The first with an example where the `\translateExerciseBank` fails (with the chinese characters).
- The second with a photo of the margin problem, or an example that recreates it.

I will look into it when I have the time. Thank you.

**Comment by mayoutu** [comment]
Hi Strauman, I'm back.

I was very busy and I just used your new package and it still has the same problems:

1) Translation to Chinese characters cannot be recognized;
2) Narrow margin problem.

Please see the attached figure.
![untitled](https://user-images.githubusercontent.com/38101830/40884620-9b9e9e20-6706-11e8-859f-19a619886b22.png)

**Comment by Strauman** [comment]
Hey! I'm also very busy!

Did you try the workaround I proposed in #9 ?
```
% Before \begin{document}, try this:
\makeatletter
\gdef\exbank@opt@problemHeader{\normalfont\Large\bfseries TRANSLATION~\theproblemcounter}
\gdef\exbank@opt@solutionHeader{\large{\textbf{TRANSLATION}}}
\makeatother
```
I haven't had time to fix the margin problem, but I might get to it in a couple of weeks.

**Comment by mayoutu** [comment]
That works for Chinese characters, thanks!!

I will wait for your update. Take it easy!

**Comment by balodja** [comment]
I have encountered the same bug for cyrillic characters. The workaround works like a charm, thanks.
