### ISSUE TITLE
Exercise 11 from external file not displayed with pre-release

### ISSUE THREAD

**Issue by tristelune1** [Strauman/exercisebank#60]
Hi,

I have really a strange behavior. I have the following:

    \makeset[nohead]{myExerciseSet}{\select{databaseGm}{11}}
     \buildset{myExerciseSet}

When I compile, I get no error and an empty page. It's the same for all external file. If I try to display the exercise 11, it's always the same behavior. If I add a dummy exercise, for example:

```
\begin{problem}
Hello
\end{problem}
\begin{solution}
The end
\end{solution}
```
and let's say it's the new exercise 11, the old one is displayed. This dummy exercise can't be displayed. What is strange, is that there is no problem with the version 0.2.0. 

Is it the same for you ? If no, I'll try to create a simplified version.

**Comment by Strauman** [comment]
Ah, the 11-bug. Had a similar issue when building `\makeset{11}{somefile}`. I don't really remember what was wrong, but I'll look into it.

**Comment by Strauman** [comment]
Huh. Turns out I'm using `\if` wrong here!

**Comment by Strauman** [comment]
Note to self:
`\def\content{aa}\if\content\relax TRUE \else FALSE\fi` returns true because the "if" evaluates to
`\if aa\relax` which is true.

**Comment by Strauman** [comment]
Should be good in build 88

**Comment by tristelune1** [comment]
I thought twice before I reported this bug, because I had a strange feeling! I was sure I was doing something wrong!!

Thank you, now it works. As you know, next bug ;-).
