### ISSUE TITLE
Show only solutions

### ISSUE THREAD

**Issue by thorstengrothe** [Strauman/exercisebank#62]
I got an idea for a new feature. I think it would be useful to have a command that show only the solutions of an exercise - that would reduce much space, like so

```
\begin{problem} --> hide this env when \ShowSolutionsOnly is on
problem
\end{problem}
\begin{solution}
Solution for the problem
\end{solution}
```

Regards
Thorsten

**Comment by tristelune1** [comment]
Great Idea! For me it would be enough, if only all the solutions are displayed. It would be not necessary to choose at the exercise level.

**Comment by Strauman** [comment]
It's actually implemented, but not thoroughly tested or documented. I don't even know if it works properly: `\SolutionsOnly`

**Comment by Strauman** [comment]
@thorstengrothe @tristelune1 I'm gonna set up Travis CI for testing. I'd need files that does testing. Would you guys care to collaborate and help me make said files? 

What I ultimately need is to have files that verifies documented functionality. This way things are automatically tested using those files!

Travis CI would run `latexmk` on the generated test files, and give an error if it failed at all.
Would you help me out with this?

**Comment by thorstengrothe** [comment]
I can sent you a couple of files, but you need to include my personal *.sty file, otherwise it won't compile and you have to compile with `xelatex`, would this help? Maybe the simplest way would be a compressed *.zip file.

**Comment by Strauman** [comment]
@thorstengrothe I'm still working on Travis. I'm mainly building on `pdflatex`. The thing is that the test files should be made from scratch for that exact purpose. I'll show you guys an example when I get that far :)

**Comment by Strauman** [comment]
@thorstengrothe @tristelune1 In the [develop](https://github.com/Strauman/exercisebank/tree/develop) branch you can now see a [tests](https://github.com/Strauman/exercisebank/tree/develop/tests) directory. It contains multiple things. See how the [tests/sanitycheck/main.tex](https://github.com/Strauman/exercisebank/tree/develop/tests/sanitycheck/main.tex) is made, and you can make similar structures. Exercises are located in [tests/exercises](https://github.com/Strauman/exercisebank/tree/develop/tests/exercises). You can read more on how the tests would work [here](https://github.com/Strauman/travis-latexbuild). The best would be if you could clone this git, change stuff and make pull requests to this github with your tests.  (Then the tests would actually be run!).

Also: If you have docker installed and are on OS X or Linux, you can use `./runtests.sh` to run the tests locally on your computer.

**Comment by tristelune1** [comment]
@Strauman , sorry I didn't read the new comments here. I don't know Travis, I'll have a look at the structure of the tests and provide some test files. By the way, thank you for the last build!

**Comment by thorstengrothe** [comment]
Me too, but I will need some time for this, cause I have I a lot of personal macros for my problems...

**Comment by Strauman** [comment]
Take the time you'd need. Start by forking this repo (top right of this page it says "fork"). That is making a copy of your repo. Then you can follow [this guide](https://help.github.com/articles/committing-changes-to-a-pull-request-branch-created-from-a-fork/) :)

**Comment by tristelune1** [comment]
Thank you! But probably at the beginning it won't probably exactly fit to your expectations :wink:

**Comment by Strauman** [comment]
@tristelune1 I know there is a learning curve and will be sure to appreciate any effort :)

**Comment by thorstengrothe** [comment]
> It's actually implemented, but not thoroughly tested or documented. I don't even know if it works properly: `\SolutionsOnly`

I tested the command but here with the latest prerelase it does the same as `\DisplaySolutions`. I would be great to get the command running...

Thorsten

**Comment by Strauman** [comment]
I'm on it! :)

**Comment by thorstengrothe** [comment]
That's good news !

**Comment by thorstengrothe** [comment]
@Strauman 
 
I think there is a small bug in the new prerelease `exercisebank-0.2.3b104-prerelease`.
Take the test file shipped with  the release `example.tex` and set

`\DisplaySolutions`
or
`\SolutionsOnly`

I got for both options a error message:

```
! Undefined control sequence.
\tighten@paragraph@solutions ...f \@SolutionsOnly 
                                                  \@isFalse \if \@DisplaySol...
l.9 \end{solution}
```
I searched a bit in the source code but I cannot find the error, my programming skills are to weak for this unfortunately :-)

**Comment by Strauman** [comment]
Huh. I'll look into it! See #84
