### ISSUE TITLE
Problem not tagged is showed

### ISSUE THREAD

**Issue by tristelune1** [Strauman/exercisebank#65]
Hello, consider this main file:

```
\documentclass[a4paper]{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[french]{babel}
\usepackage{etoolbox}
\usepackage{graphicx}
\usepackage{hyperref}
\usepackage{exercisebank}


\exercisebanksetup{exercise
  directory=/home/user/Mes_Documents/prof/cours_exercices/bank/,
figure root
directory=/home/user/Mes_Documents/prof/cours_images/math/,
part problems=Off}

\makeset[nohead]{myExerciseSet}{databasedummy}

\DisplaySolutions
\ShowNumbers
\translateExBank{Problem=Exercice}


\begin{document}

\date{}

\buildtags{fiche2}{myExerciseSet}

  
\end{document}
```

And this external file `databasedummy`:

```
\begin{problem}
  Problem 1
\end{problem}
\begin{solution}
  Solution 1
\end{solution}
\nextproblem{tag=fiche2}
\begin{problem}
  Problem 2
\end{problem}
\begin{solution}
  Solution 2
\end{solution}
\nextproblem{tag=fiche2}
\begin{problem}
  Problem 3
\end{problem}
\begin{solution}
  Solution 3
\end{solution}
```

After compilation, for me the first problem should not be displayed. But I have all three problems in my document, even if the first problem is not tagged.

**Comment by Strauman** [comment]
I Isn't this the same as #64? If it is, then it should've been fixed already :)

**Comment by tristelune1** [comment]
Unfortunately not :disappointed:.  In #64 , you have two problems, and both are tagged. In my example, we have three problems:

- the first **is not tagged**
- the second and third are tagged

If we create the exercise sheet with the tag of problem 2 and 3, we also have the first. It's probably possible to construct an similar case with only two problems. There was similar problems when the first has `\nextproblem` at the beginning or not.

**Comment by tristelune1** [comment]
Now it works as expected, thanks! :+1:
