### ISSUE TITLE
First page has only the title

### ISSUE THREAD

**Issue by tristelune1** [Strauman/exercisebank#69]
Hi, I have a strange behavior. For the moment I include the files in my message. I still have to look how I can integrate this example to your tests. My main file:

```
\documentclass[a4paper]{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[french]{babel}
\usepackage{etoolbox}
\usepackage{graphicx}
\usepackage{hyperref}
\usepackage{exercisebank}

\title{My exercises}

\exercisebanksetup{exercise
  directory=/home/user/Mes_Documents/prof/cours_exercices/bank/,
figure root
directory=/home/user/Mes_Documents/prof/cours_images/math/,
part problems=Off}

\makeset[nohead]{myExerciseSet}{\select{databasedummy}{2}}

\DisplaySolutions
\ShowNumbers
\translateExBank{Problem=Exercice}


\begin{document}

{\Large

\maketitle{}

\date{}

\buildset{myExerciseSet}

}
  
\end{document}
```

The `dummydatabase`

```
\begin{problem}
  Problem 3
\end{problem}
\begin{solution}
  Solution 3
\end{solution}
\begin{problem}
  
  Effectuer les soustractions suivantes en utilisant la méthode du complément:

\newcommand\NbDouzeA{67 - 29}
\newcommand\NbDouzeB{72 - 28}
\newcommand\NbDouzeC{54 - 25}
\newcommand\NbDouzeD{96 - 28}
\newcommand\NbDouzeE{85 - 36}
\newcommand\NbDouzeF{78 - 19}
\newcommand\NbDouzeG{86 - 38}
\newcommand\NbDouzeH{63 - 34}
\newcommand\NbDouzeI{74 - 35}
\newcommand\NbDouzeJ{57 - 18}
  
  \begin{enumerate}
    \renewcommand{\theenumi}{\alph{enumi}}
    \renewcommand{\labelenumi}{\theenumi)}
  \item $\NbDouzeA = $
  \item $\NbDouzeB = $
  \item $\NbDouzeC = $
  \item $\NbDouzeD = $
  \item $\NbDouzeE =$
  \item $\NbDouzeF = $
  \item $\NbDouzeG = $
  \item $\NbDouzeH = $
  \item $\NbDouzeI = $
  \item $\NbDouzeJ = $
\end{enumerate}
\end{problem}
\begin{solution}
  \begin{enumerate}
    \renewcommand{\theenumi}{\alph{enumi}}
    \renewcommand{\labelenumi}{\theenumi)}
  \item $\NbDouzeA = 38$ 
  \item $\NbDouzeB = 44$ 
  \item $\NbDouzeC = 26$ 
  \item $\NbDouzeD = 68$ 
  \item $\NbDouzeE = 49$ 
  \item $\NbDouzeF = 29$ 
  \item $\NbDouzeG = 59$ 
  \item $\NbDouzeH = 48$
  \item $\NbDouzeI = 39$
  \item $\NbDouzeJ = 39$ 
  \end{enumerate}

\end{solution}
```

You will see the selected problem is on page two after compilation. Possible workaround:
- in the main file, delete the `{\Large      }` block. Unfortunately it is not always possible. 
- If I have only one problem in my database it seems to work. Juste comment the first problem and there will be no blank page. 

With the version 0.2.0 there is no problem.

**Comment by Strauman** [comment]
Try `\exercisebanksetup{tighten paragraphs=False}`

**Comment by Strauman** [comment]
That would turn on the "tightening" of the paragraphs: exercisebank has a setup that attempts to contain all part problems to stay on one page. That is, trying to prevent that part problems are split across multiple pages. So `\exercisebanksetup{tighten paragraphs=False}` disables this functionality.

**Comment by thorstengrothe** [comment]
Yes, and this feature is extreme useful, neither eqexam nor xsim has this implemented. I often spend a lot of time to insert manual pagebreaks to get this work. I have an idea for a new feature to handle this problem.

If it would be possible to rearrange the order of the problems with `\select`, one could select a problem that fits to the page per hand, like so:

```
\makeset{3}{\select{secondexercise}{2,1}} --> show 2 first
\makeset{3}{\select{secondexercise}{1,2}} --> show 1 first
```
At the moment the order of the numbers has no effect, right?

Regards
Thorsten

**Comment by Strauman** [comment]
1. Did it work turning off `tighten paragraphs`?
1. Making ordered select is now a new issue (#70).

**Comment by tristelune1** [comment]
@Strauman Sorry, yesterday I had a nice surprise: my computer didn't start. So I had a nice day configuring a dual boot :disappointed_relieved: on another computer. 

Yes, `tighten paragraphs` works perfectly for me, thank you!

**Comment by Strauman** [comment]
That sucks! Is your computer okay?

**Comment by tristelune1** [comment]
Today it wasn't better. Now it was send for a check and to be repaired. What I discovered is that it won't be repaired in my country, not even in a country which has a boundary where I live. It's incredible!

**Comment by tristelune1** [comment]
Hi, I'm afraid we have to reopen this issue. I have again the same problem. Sorry for not making a pull request, but it was a lot of work to simplify the example and to understand a little bit what happens. The main file is the following:

```
\documentclass[a4paper]{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[french]{babel}
\usepackage{graphicx}
\usepackage{exercisebank}
\usepackage{caption}

\title{My exercises}

\exercisebanksetup{exercise
  directory=/home/user/Mes_Documents/prof/cours_exercices/bank/,
figure root
directory=/home/user/Mes_Documents/prof/cours_images/math/,
part problems=Off,
tighten paragraphs=False}
\makeset[nohead]{myExerciseSet}{databasedummy}

\DisplaySolutions
\ShowNumbers
\translateExBank{Problem=Exercice}

\begin{document}


{\Large

\maketitle{}

%\buildset{myExerciseSet}
\buildtags{fiche2_D1}{myExerciseSet}

}
  
\end{document}
```

The `databasedummy` [is on pastebin here](http://pastebin.fr/54541). You will see, it has a lot of problems. I have some external files with about 70-80 problems at the moment. 

If you compile the file, the first page is blank. What I noticed:

1. It's better if you set `tighten paragraphs=True`, but still not ok.
2. If you comment `\Displaysolutions` it works perfectly. 

Try to delete some problems and it will be better. Perhaps you add some spaces somewhere and when there is a lot of problems, the first one is on the second page with the solution. It was tested with the last prerelease.
