### ISSUE TITLE
Titles are missing when using short side margins

### ISSUE THREAD

**Issue by mayoutu** [Strauman/exercisebank#8]
![feedback](https://user-images.githubusercontent.com/38101830/38408467-36cba888-396d-11e8-92ef-0f5537fc7681.png)

I changed the titles to P and S. They don't display well when I set short side margins.

The figure also shows poor paragraphing between the solution and the next exercise.

**Comment by Strauman** [comment]
Paragraphing is already taken care of. I will look into the margins for 0.1.1 :)
Thank you for your issue!

**Comment by Strauman** [comment]
I have made issues #16 and #17 that should provide a fix for using short side margins, as soon as it's implemented!

**Comment by Strauman** [comment]
In the __upcoming__ version do `\exercisebanksetup{style margins=off}`
