### ISSUE TITLE
Problem with tag selections maybe new bug?

### ISSUE THREAD

**Issue by thorstengrothe** [Strauman/exercisebank#81]
With `\buildtags{easy}{tags}` the tag selection is not working. Result:

![bildschirmfoto_2018-10-03_10-08-14](https://user-images.githubusercontent.com/19598706/46404287-09530600-c705-11e8-8f35-6f7da0156983.png)

These are the files:

```
%!TEX root = ../example.tex
%\nextproblem{hide}
\begin{intro}
	Testing the tags
\end{intro}
\nextproblem{tag=easy}
\begin{problem}
  Easy
\end{problem}
\begin{solution}
	Easy
\end{solution}
\nextproblem{tag=difficult}
\begin{problem}
  Difficult
\end{problem}
\begin{solution}
	Difficult
\end{solution}
\nextproblem{tag=hard}
\begin{problem}
  hard
\end{problem}
\begin{solution}
	hard
\end{solution}
```
And the main file
```
\documentclass{article}
\usepackage{exercisebank}
\usepackage{lipsum}
\exercisebanksetup{exercise directory=exercises}

\makeset{tags}{tagtest}

%\ShowTags

\begin{document}

\buildtags{easy}{tags}

\end{document}
```
Is this my fault? I'm using exercisebank v0.2.1/95 here.

**Comment by Strauman** [comment]
You're right?! I pushed something that didn't work :(

On it.

**Comment by thorstengrothe** [comment]
Good to hear that, I thought it was my fault :-)

**Comment by Strauman** [comment]
Here is the new [prerelease](https://github.com/Strauman/exercisebank/releases/tag/0.2.2b96-prerelease)

**Comment by thorstengrothe** [comment]
Until now it works for me after a few tests :-)
Thanks for the fast fix!

**Comment by Strauman** [comment]
Fix pushed to CTAN
