### ISSUE TITLE
Part problem header shows twice and unappropriately when itemize is used

### ISSUE THREAD

**Issue by Strauman** [Strauman/exercisebank#85]
Thanks for the fix, the error is gone and all solutions are displayed fine. One thing remains, if you have a `itemize` oder `enumerate` env in the solutions like so:
```
\begin{solution}
	\begin{itemize}
		\item test
		\item test
		\item \lipsum[4]
	\end{itemize}
\end{solution}
```

than these environments are counted by the part problem counters, see here:
![bildschirmfoto_2018-11-04_10-26-57](https://user-images.githubusercontent.com/19598706/47962954-a1098400-e024-11e8-917b-a5dffc42d9a0.png)

_Originally posted by @thorstengrothe in https://github.com/Strauman/exercisebank/issues/84#issuecomment-435658040_

**Comment by thorstengrothe** [comment]
Great, works perfectly until now, thanks for the super fast support. I will test and report any bug I'll find in the future :-) P.S. The package get's better and better!

**Comment by Strauman** [comment]
@thorstengrothe Thanks for your help :D 👍
