### ISSUE TITLE
Point system: unable to display points

### ISSUE THREAD

**Issue by tristelune1** [Strauman/exercisebank#92]
Hi,

This time I want to use the point system, but unfortunately it doesn't work. What I expect: if I have

    \nextproblem{points=3}

Those points will be displayed in the exercise sheet, but it's not the case. 

My files:

```
\documentclass[a4paper]{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[french]{babel}
\usepackage{graphicx}
\usepackage{exercisebank}
\usepackage{caption}

\title{My exercises}

\exercisebanksetup{exercise
  directory=/home/user/Mes_Documents/prof/cours_exercices/bank/,
figure root
directory=/home/user/Mes_Documents/prof/cours_images/math/,
part problems=Off,
tighten paragraphs=False}
\makeset[nohead]{myExerciseSet}{\select{databasedummy}{1}}

\DisplaySolutions
\ShowNumbers
\translateExBank{Problem=Exercice}

\begin{document}


\maketitle{}

\buildset{myExerciseSet}
  
\end{document}
```

My database:

```
\nextproblem{points=3}
\begin{problem}
Problem 1
\end{problem}
\begin{solution}
Res1
\end{solution}
\begin{problem}
Prob2 
\end{problem}
\begin{solution}
Res2
\end{solution}
\begin{problem}
Prob3
\end{problem}
\begin{solution}
Res3
\end{solution}
```

I sure it works for you, but I'm getting crazy, something is wrong or there is an issue on my system. What I discovered:

- it seems you use the package 'marginnote'. It wasn't installed on my system. Could it be a problem ? 
- If I use `\totalpoints` I get 0.
- If I use `\totalpoints` and I comment
    part problems=Off
I get 0. If I compile a second time, I get "3" as expected. 

If it can help you, I'll try to add this in your test suite. 

Your help is welcome :wink:

**Comment by Strauman** [comment]
I'm a little overwhelmed with work at the moment. I'll take a look at it some time next week or the week after :)

**Comment by tristelune1** [comment]
Thank you for your answer. No problem, I'll wait. You know now why I disappeared for several weeks ;-).  I was busy with your package!

**Comment by tristelune1** [comment]
I've tested now, and it still doesn't work. Does it work in your system ?

**Comment by Strauman** [comment]
I don't know. I'll have a look :)

**Comment by Strauman** [comment]
There was a bug that wouldn't show the points on the first part problem. This is now fixed and will be released shortly. However, the "point display" is a part of the "part problem" header. That means if you do `part problems=false`, it's not going to show. `part problems=false` removes the need for part problems entirely and will consider any `problem` environment as a completely new problem, and is not designed to use the point system. Also, the `nohead` argument does not work together with `part problems off`. Here is a suggested workaround;

```
\documentclass[a4paper]{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[french]{babel}
\usepackage{graphicx}
\usepackage{exercisebank}
\usepackage{caption}
\usepackage{filecontents}
\begin{filecontents}{databasedummy}
	\nextproblem{points=3}
	\begin{problem}
		Problem 1
	\end{problem}
	\begin{solution}
		Res1
	\end{solution}
	\nextproblem{points=2}
	\begin{problem}
		Prob2
	\end{problem}
	\begin{solution}
		Res2
	\end{solution}
	\begin{problem}
		Prob3
	\end{problem}
	\begin{solution}
		Res3
	\end{solution}
\end{filecontents}

\title{My exercises}

\makeatletter
\exercisebanksetup{exercise directory=bin/,
	part problems=true,
	% Hide part problem header
	part problem header={},
	% Hide the point system style (to get in an exercise header)
	current points style={},
	tighten paragraphs=false
}
% Make a header conatining points, and trigger it at appropriate place using hook
\At\VeryBeginPartproblem{{\par\noindent\Large\bfseries\@tr{Problem}~\thepartproblemcounter~--~\exb@currentPoints p}\\}
\makeatother
\makeset[nohead]{myExerciseSet}{\select{databasedummy}{1}}

\DisplaySolutions
\ShowNumbers
\translateExBank{Problem=Exercice}

\begin{document}
	\buildset{myExerciseSet}
\end{document}
```

**Comment by tristelune1** [comment]
Hhhmmm, I'm afraid your workaround is not possible for me. First I let you clarify #95 . Then we can discuss this. In short: my files have much more than 3 problems, it's not possible to include them like your suggestion :worried: .

**Comment by tristelune1** [comment]
Issue  #95 will be closed. So you can also close this one. I will split my files in smaller files. So the point system works, excepted for another feature I would like. After writing this command I will write it. 

For me you can close this issue.
