### ISSUE TITLE
Multiple problems (exercises) in one file - Problems structure

### ISSUE THREAD

**Issue by tristelune1** [Strauman/exercisebank#95]
Hi,

This question follow the issue #92. 
Suddenly, I'm not sure anymore I understand your package well. At the beginning I tried and found a solution which worked for me. But I'm not sure it was your idea. From the documentation I understand now: 

- one problem with some partproblems -> one file. 

Let's say the following, I have the following problem:

```
Compute the area of the following circles:
a) the radius is 5cm
b) the diameter is 5cm
```

It's one problem with two partproblems. Consider a second one:

```
The length of a square's side is 5 cm.
a) Compute the area of the square
b) Compute the perimeter of the square
``` 
The idea of the package is two create two files, one file for each problem. Is it right ? 

At the moment I have only one file in that case. Both problems are geometry problems, so I've put them in a file named `databasegeometry`. I've disabled the part problems option.

**Comment by Strauman** [comment]
I can attempt to make some different approach to this, so you can have multiple exercises in one file.

**Comment by tristelune1** [comment]
Perhaps it's not necessary. For me mixnmatch is very interesting, but for the moment I can't use it. 
If I would change the structure of the exercises, I would be able to use the point system and  to use mixnmatch for example. It would need a lot of time, but if there is a benefit there is no problem. 
The problem is I don't know how I could manage all files. I have at least 400 problems, perhaps 500 and it's growing. How could I search some problems ? For the moment it's very convenient: I display all problems from a file, I pick the exercise numbers and I add them to the selected exercises. If I missed something, perhaps it's not necessary to add a feature.

**Comment by Strauman** [comment]
Shouldn't be too much work, but I'll probably not look at it until the newyear. Merry christmas :)

**Comment by tristelune1** [comment]
No problem, I'll wait for this New Year gift ;-). Thank you for all your work!

**Comment by Strauman** [comment]
What if you do
```
\makeatletter
\newcommand\exercise{
\ifexb@isFirstProblem%
    \global\exb@isFirstProblemfalse%
  \else%
    \Trigger\EndProblem%
  \fi%
% \ifhmode\else\par\fi
\par
  \Trigger\BeginProblem%
  \Trigger\VeryBeginProblem%
}
\makeatother
```
And then you just write `\exercise` between the exercises?

**Comment by tristelune1** [comment]
I have tried, but there are still some problems. But I need to test more to understand the problem. After I will report them. 

For me there is still the option to split my big files in small ones, because I could use the mixnmatch features for example. But one thing is not clear to me: my goal is to choose some exercises in a set easily. When all exercises are in one big file, it's as easy as:

    \select{databasegeometry}

for example to select all exercises related to geometry. When all geometry exercises are split in multiple files, how can I select them all at once to be able to choose some of them ?

**Comment by Strauman** [comment]
That is `\nextproblem{tags={list,of,tags}}` before part problems and then use the commands `\buildtags` and `\HideTags` as described in [the docs](https://github.com/Strauman/exercisebank/blob/master/release/exercisebank-doc.pdf) :)

**Comment by tristelune1** [comment]
At first, I thought, I'm really stupid. But I need to check, because I'm not sure it works. Or if I say it otherwise: perhaps there is problem with a small detail. How can I include the files in which there is the geometry tag. I check it and try it tomorrow. Perhaps I will feel very bad tomorrow ;-).

**Comment by Strauman** [comment]
@tristelune1 If you have read the docs, and still don't understand, then either something does not work, or the docs aren't good enough. Here is a complete example that I get to work just fine:


```
\documentclass[a4paper]{article}
\usepackage{exercisebank}
\usepackage{filecontents}

\begin{filecontents}{myproblems.tex}
\nextproblem{tags=geometry}
\begin{problem}
  This is geometry problem 1 of 3
\end{problem}
\begin{solution}
  This is solution to geometry problem 1
\end{solution}
\nextproblem{tags=geometry}
\begin{problem}
  This is geometry problem 2 of 3. It does not have a solution.
\end{problem}
\nextproblem{tags=not geometry}
\begin{problem}
  This is not a geometry problem, and should not be shown when the geometry tag is built
\end{problem}
\nextproblem{tags=geometry}
\begin{problem}
  This is geometry problem 3 of 3
\end{problem}
\begin{solution}
  This is solution to geometry problem 3
\end{solution}
\end{filecontents}
\title{My exercises}

\makeset{myExerciseSet}{myproblems}
\begin{document}
	\buildtags{geometry}{myExerciseSet}
\end{document}
```

Let me know if you can't get it to work!

**Comment by tristelune1** [comment]
I'm must be a real pain at the moment ;-). 

The problem is probably: I can't achieve what I want, because I didn't explained well my workflow. I understand your example and thank you very much for it. What I don't like: if I understand correctly, I need to add the part between 
```
     \begin{filecontents}
     ....
     \end{filecontents}
```
In each exercisesheet. If I want to use the third exercise in two different exercise sheets, I need to write it two times. If there is a mistake, I have to modify it in two files. I don't want it, the goal of your package is also to solve this problem. 

So I have one big file with a lot of problems. For the geometry it's about 70 I think  for other it's can be as much as 200. By the way your package is very fast!

If there is a mistake, I do the correction and because I include each time the same portion of code, it's corrected for all exercise sheets. With that structure, I can't use the point system, because in my big file I don't have subproblems, but really different problems. For example:

```
File myproblems.tex

\nextproblem{tags=geometry}
\begin{problem}
  This is geometry problem 1 of 3
\end{problem}
\begin{solution}
  This is solution to geometry problem 1
\end{solution}
\nextproblem{tags=geometry}
\begin{problem}
  a) First question of second problem
  b) Second question of second problem
  c) One last question
\end{problem}
\begin{solution}
There is no solution
\end{solution}
\nextproblem{tags=not geometry}
\begin{problem}
  a) First question of the third problem
  b) Second question of the third problem
\end{problem}
\begin{solution}
  a) Solution of first question
  b) Solution of second problem
\end{solution}
```

When I need a new geometry problem, I use 

```
\makeset{myExerciseSet}{myproblems}
```
And I have an overview of all problems. I choose some of them with a `select` command and everything is fine. It's fast to choose some problems. 

Let's say I need to split the big files in one file per exercise. Let's say: 

exercise1.tex

```
\nextproblem{tags=geometry}
\begin{problem}
  This is geometry problem 1 of 3
\end{problem}
\begin{solution}
  This is solution to geometry problem 1
\end{solution}
```
The same idea for exercise2.tex and exercise3.tex

Now to have an overview I need in my tex file:

    \makeset{myExerciseSet}{exercise1,exercise2,exercise3}

Then I delete or exclude what I don't want. If I have 70 exercise, this line is a pain to write. I can't use somethine like

        \makeset{myExerciseSet}{exercise{1..3}}

Because they are different files. I should write the 70 files. Sometimes in an exercise sheet there is some geometry problems and I need something from another chapter. To have an overview I should write perhaps 70 files and the 100 files related to the other subject. I don't have a regular expression, a construct to select them all. For example

        \makeset{myExerciseSet}{geometry/*, numbers/*}

Here I have selected all files from geometry and all files from numbers. I doesn't exist, it's to give you the idea. If such a feature would be available, or perhaps I didn't see it, it would be a possibility to split my big files. I can use tags, but I *need* to include all files first. 

Briefly: I want to have an overview of all problems related to a theme without writing a looooooonnngggg list of files in the preamble. 

I hope I was able to explain better what I want.

**Comment by Strauman** [comment]
`filecontents` is just writing to a file, so no. E.g.

```
\begin{filecontents}{myfile.tex}
CONTENTS
\end{filecontents}
```
is the same as making `myfile.tex`, adding `CONTENTS` to the file and then do `\input{myfile}`.

For including all 70 files you could possibly do
```
\xdef\exercisefiles{exercise1}
\foreach\i in {2,...,70}{%
\xdef\exercisefiles{\unexpanded\expandafter{\exercisefiles},exercise\i}
}
\edef\makesetargs{{myExerciseSet}{\exercisefiles}}
\expandafter\makeset\makesetargs
```
which would be equivalent to doing `\makeset{myExerciseSet}{exercise1,exercise2,........}` all the way to `exercise70`.

Sorry for brief response, I'll make sure I proof read your question later.

**Comment by tristelune1** [comment]
Thank you for your answer. Now I need time to test everything. Because at the end I could end with splitting my big files...... it will be a piece of cake! In that case I have to write some scripts to do the job for me. 
I'll give you some news probably next week.

**Comment by tristelune1** [comment]
Thank you for your code. It works for me! It's not as convenient as a `select`, but it's enough!

For me you can close this issue.
