### ISSUE TITLE
true/false questions randomization possible?

### ISSUE THREAD

**Issue by thorstengrothe** [Strauman/exercisebank#96]
I made a personal true/false environment like in exam.cls with `enumitem` :

```
% True/False questions like in eqexam --> needs \usepackage{enumitem}
% https://tex.stackexchange.com/questions/349470/underline-colored-text-with-linebreak
\newcommand\reduline{\bgroup\color{red!75!black}\markoverwith
	{\textcolor{black}{\rule[-0.5ex]{2pt}{0.4pt}}}\ULon}

% http://texwelt.de/wissen/fragen/20635/spezielle-liste-mit-enumitem-und-exsheets
\newcommand{\tf}[1]{%
 \ifisSolution --> hook for exercisebank
 \item\makebox[0pt][r]{%
 \reduline{\makebox[15mm][c]{\textcolor{red!75!black}{#1}}}
 \hspace{1mm}}\ignorespaces
 \else
 \item\makebox[0pt][r]{%
 \reduline{\makebox[15mm][c]{}}
 \hspace{1mm}}\ignorespaces
\fi
}

% Define a new list with enumitem
\newlist{truefalse}{enumerate}{1}
\setlist[truefalse]{%
  label=\alph*),
  align=left,
  labelindent=0mm,
  labelwidth=20mm,
  leftmargin=22mm,
  labelsep=!
}
```
The result with this code looks like this:
```
\begin{problem}
    Testing the true/false environment
    \par
    \medskip
    Set \ldots
    (1) for a right answer,\par
    (9) for a wrong answer.\par
    \begin{truefalse}
        \tf{1} right
        \tf{9} wrong
        \tf{1} right with long Text Lorem ipsum dolor sit amet, consetetur
        sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et
        dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et
        justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea
        takimata sanctus est Lorem ipsum dolor sit amet.
    \end{truefalse}
\end{problem}
```
![bildschirmfoto_2019-01-03_22-20-27](https://user-images.githubusercontent.com/19598706/50664692-3d60f000-0fae-11e9-85fd-a5ff028938aa.png)

And here the solution displayed
```
\begin{solution}
    Testing the true/false environment
    \par
    \medskip
    Set \ldots

    (1) for a right answer,\par
    (9) for a wrong answer.\par
    \begin{truefalse}
        \tf{1} right
        \tf{9} wrong
        \tf{1} right with long Text Lorem ipsum dolor sit amet, consetetur
        sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et
        dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et
        justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea
        takimata sanctus est Lorem ipsum dolor sit amet.
    \end{truefalse}
\end{solution}
```
![bildschirmfoto_2019-01-03_22-22-32](https://user-images.githubusercontent.com/19598706/50664760-79945080-0fae-11e9-9c0f-9ddacc820e0f.png)

This works very well, but it could be optimized a bit.

1. In `eqexam` you only have to write the problem env, the solution env is **not** needed. Solutions are shown if the `\DisplaySolutions` command in on. For now I have to write both problem and solution to show the solutions. Maybe a hook could help here. I'm using  `\ifisSolution` here. If this would be possible this would save up a lot of code.

2. It wold be nice if the  `\tf{}`  items could be randomized for example to make different groups of exams and avoid cheating...

I hope that my question is clear and understandable...

**Comment by Strauman** [comment]
1. That if exists:`\ifexb@DisplaySolutions`
2: I think this is beyond the scope of what I really want implemented in exercisebank (to keep it light weight), but I suspect you could do something with one or more of the packages from the ctan [random](https://ctan.org/topic/random) topic.

**Comment by thorstengrothe** [comment]
`\makeatletter\def\ifisSolution{\ifexb@DisplaySolutions}\makeatother` 
This works fine, thank you very much. Is it possible to make the same with `\SolutionsOnly`, I played a bit with your code, but I have no sucess..

@randomize
Ok, I see your point, the package needs to be lightwight, I agree with that, the problem with `eqexam`, `exam`, `xsim`  etc. is that they have too much features with the time. Well I will see, what I can do on my own and report...

**Comment by thorstengrothe** [comment]
Ah, that's good to know, unfortunately it helps me not for this problem. I defined a new env like this

```
\newenvironment{answerbox}[3][\linewidth]
{%
  \tcbset{%
    colframe = gray,
    colback = lightgray!20,
    fonttitle= \bfseries\small,
    boxrule = .5pt,
    before skip = 6pt,
    after skip = 3pt,
    width = #1,
    % Only when \DisplaySolutions is not on
    height = #2,
    %
    title=#3}
    \begin{tcolorbox}
     }%
  {\end{answerbox}}
```

and I only want the second argument when `\DisplaySolutions` is **not** on. I tried a couple of things with `\ifthenelse` but nothing works. Do you have an idea how to solve this?

**Comment by Strauman** [comment]
Then this should work:

```
\makeatletter\def\ifisSolution{\ifexb@DisplaySolutions}\makeatother
\newenvironment{answerbox}[3][\linewidth]
{%
	\tcbset{%
		colframe = gray,
		colback = lightgray!20,
		fonttitle= \bfseries\small,
		boxrule = .5pt,
		before skip = 6pt,
		after skip = 3pt,
		width = #1,
		% Only when \DisplaySolutions is not on
		height/.expand once = {\ifisSolution#2\else100pt\fi},
		%
		title=#3}
	\begin{tcolorbox}
}%
{\end{tcolorbox}}
\DisplaySolutions
```

The `/.expand once` expands the content once.
Possibly you could do
```
\ifisSolution\tcbset{height=#2}\fi
```

**Comment by thorstengrothe** [comment]
@Strauman thanks for your code snippet. In the meantime I changed the command with the help of xparse, which I like very much, to this:

```
\newcommand{\answerboxheight}[1]{%
  \ifisMySolution
  0cm
  \else
  #1
  \fi
}

\NewDocumentEnvironment{answerbox}{ m O{} }
{\begin{tcolorbox}[%
      colframe = gray,
      colback = lightgray!20,
      fonttitle= \bfseries,
      before skip = 6pt,
      after skip = 3pt,
      add to natural height=\answerboxheight{#1},
      width = \linewidth,
      title = Berechnung,
      #2
      ]
      \ifisMySolution
      \color{red!75!black}
      \else
      \color{lightgray!20}
      \fi}%
    {\end{tcolorbox}}
```
I did not know that it's possible to nest a command in another command. If I want to change something in another context I can simply write

```
\begin{answerbox}{2cm}[title=Test, other tcolorbox options]
    Test
\end{answerbox}
```

It works good, but I will test your snippet too :-)
