### ISSUE TITLE
Point system: sum of points for a problem

### ISSUE THREAD

**Issue by tristelune1** [Strauman/exercisebank#99]
At the moment, with the point system, the following is possible:

- to get the sum of all points with `totalpoints`
- to show the number of points for a part problem.

I would like to add the sum of points for all part problems in a problem. I mean:

````
Exercise 1 (5 points)
Part Problem 1 (1 point)
Part Problem 2(2 point)
Part Problem 3 (2 point)
````

In this example, I don't know how it's possible to get the sum of points for all part problems. I discovered recently the package [exercisepoints](https://github.com/henningkerstan/exercisepoints). You can get the documentation on [CTAN](https://ctan.org/pkg/exercisepoints?lang=de). 

In this package there is:

- one command to set the points (itempoints or points)
- `getpoint` to get the number of points for a problem. 
- `totalpoints` to get the number of points of all problems.

What is missing in exercisebank is `getpoint`. Is it possible to implement something like that...... or integrate the package `exercisepoints` ?

**Comment by Strauman** [comment]
Latest release now has a command `\exercisepoints`, which should do what you want.

**Comment by tristelune1** [comment]
Great, thank you! Tested and ok for me.
